substitutions:
  name: eastron-630v2
  device_description: "Monitor main meter EASTRON - 630M v2 modbus"

esphome:
  name: "${name}-main"
  comment: ${device_description}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
# Enable Home Assistant API
api:
  encryption:
    key: "LGZHXwqHe7uayI1fFex6pPO0xLTpcipoeiHAeFas+58="

ota:
  - platform: esphome
    password: "123456"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


web_server:
  port: 80
  auth: 
    username: admin
    password: 'admin'

  # Enable fallback hotspot (captive portal) in case wifi connection fails


output:
  - platform: gpio
    pin: GPIO2
    id: WIFI_LED     

uart:
  id: mod_uart
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600
  stop_bits: 1
  parity: NONE

modbus:
  send_wait_time: 500ms
  uart_id: mod_uart
  id: mod_bus
  

modbus_controller:
  - id: SDM630
    modbus_id: mod_bus
    update_interval: 5s
    address: 0x1
    setup_priority: -10

sensor:
  - platform: modbus_controller
    name: sdm630_phase_1_line_to_neutral_volts
    address: 0
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_sdm630_phase_2_line_to_neutral_volts
    address: 2
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_3_line_to_neutral_volts
    address: 0x4
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_1_current
    address: 6
    register_type: read
    accuracy_decimals: 3
    value_type: FP32
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_2_current
    address: 0x8
    register_type: read
    accuracy_decimals: 3
    value_type: FP32
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_3_current
    address: 10
    register_type: holding
    accuracy_decimals: 3
    value_type: FP32
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_1_power
    address: 12
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_2_power
    address: 14
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    filters: 
      - multiply: 0.001
          

  - platform: modbus_controller  
    name: sdm630_phase_3_power
    address: 16
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_1_va
    address: 18
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "VA"
    device_class: "energy"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_2_va
    address: 20
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "VA"
    device_class: "energy"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_3_va
    address: 22
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "VA"
    device_class: "energy"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_1_va_reactive
    address: 24
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "VAr"
    device_class: "energy"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_2_va_reactive
    address: 26
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "VAr"
    device_class: "energy"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_phase_3_va_reactive
    address: 28
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "VAr"
    device_class: "energy"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_sum_of_line_currents
    address: 48
    register_type: read
    accuracy_decimals: 3
    value_type: FP32
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"

  - platform: modbus_controller  
    name: sdm630_total_system_power
    address: 52
    register_type: read
    accuracy_decimals: 3
    value_type: FP32
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"


           

  - platform: modbus_controller
    name: sdm630_total_system_va
    address: 56
    register_type: read
    accuracy_decimals: 3
    value_type: FP32
    unit_of_measurement: "kVA"
    device_class: "power"
    state_class: "measurement"
    filters:
      - multiply: 0.001

  - platform: modbus_controller
    name: sdm630_total_system_var
    address: 60
    register_type: read
    accuracy_decimals: 3
    value_type: FP32
    unit_of_measurement: "kVAr"
    device_class: "power"
    state_class: "measurement"
    filters:
      - multiply: 0.001

  - platform: modbus_controller
    name: sdm630_frequency_of_supply_voltages
    address: 70
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "Hz"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_import_wh_since_last_reset
    address: 72
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "kWh"
    device_class: "energy"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_export_wh_since_last_reset
    address: 74
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "kWh"
    device_class: "energy"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_maximum_total_system_power
    address: 86
    register_type: read
    accuracy_decimals: 3
    value_type: FP32
    unit_of_measurement: "kW"
    device_class: "power"
    state_class: "measurement"
    filters:
      - multiply: 0.001

  - platform: modbus_controller
    name: sdm630_total_system_va_demand
    address: 100
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "VA"
    device_class: "power"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_maximum_total_system_va_demand
    address: 102
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "VA"
    device_class: "power"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_line_1_to_line_2_volts
    address: 200
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_line_2_to_line_3_volts
    address: 202
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"

  - platform: modbus_controller
    name: sdm630_line_3_to_line_1_volts
    address: 204
    register_type: read
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "V"
    device_class: "voltage" 
    state_class: "measurement"

text_sensor:

  # Wifi Info
  - platform: wifi_info
    ip_address:
      name: "${name} IP"
    ssid:
      name: "${name} SSID"
    mac_address:
      name: "${name} MAC"    