substitutions:
  name: jk-baterry-modbus
  device_description: "JK BMS Baterry monitor modbus"
  external_components_source: github://syssi/esphome-jk-bms@main

esphome:
  name: "${name}-main"
  friendly_name: JK_Baterry_modbus
  comment: ${device_description}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "m2Aq5QCaN1uTiICCROnbPIq3zzHKRnRuP2HPuqWQc9s="

ota:
  - platform: esphome
    password: "123456"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jk-Baterry-Modbus"
    password: "12345678"

#web_server:
  #port: 80
  #auth: 
    #username: admin
    #password: 'admin'

output:
  - platform: gpio
    pin: GPIO2
    id: WIFI_LED     

uart:
  id: mod_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1
  parity: NONE

modbus:
  send_wait_time: 50ms
  uart_id: mod_uart
  id: mod_bus

modbus_controller:
  - id: bms0
    modbus_id: mod_bus
    update_interval: 5s
    address: 0x1
    setup_priority: -10

binary_sensor:

# Status WiFi
  - platform: status
    name: "${name} Online"
    id: wifi_status
    device_class: connectivity
    on_press:
      - output.turn_on: WIFI_LED
    on_release:
      - output.turn_off: WIFI_LED
sensor:
- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 0 Voltage"
  register_type: holding
  address: 0x1200
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 1 Voltage"
  register_type: holding
  address: 0x1202
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 2 Voltage"
  register_type: holding
  address: 0x1204
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 3 Voltage"
  register_type: holding
  address: 0x1206
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 4 Voltage"
  register_type: holding
  address: 0x1208
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 5 Voltage"
  register_type: holding
  address: 0x120a
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 6 Voltage"
  register_type: holding
  address: 0x120c
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 7 Voltage"
  register_type: holding
  address: 0x120e
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 8 Voltage"
  register_type: holding
  address: 0x1210
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 9 Voltage"
  register_type: holding
  address: 0x1212
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 10 Voltage"
  register_type: holding
  address: 0x1214
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 11 Voltage"
  register_type: holding
  address: 0x1216
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 12 Voltage"
  register_type: holding
  address: 0x1218
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 13 Voltage"
  register_type: holding
  address: 0x121a
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 14 Voltage"
  register_type: holding
  address: 0x121c
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 15 Voltage"
  register_type: holding
  address: 0x121e
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell 16 Voltage"
  register_type: holding
  address: 0x1220
  unit_of_measurement: "mV"
  value_type: U_WORD




- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell average Voltage"
  register_type: holding
  address: 0x1244
  unit_of_measurement: "mV"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Cell Voltage max diff"
  register_type: holding
  address: 0x1246
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 3
  filters: 
    - multiply: 0.001

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "MOS Temperature"
  register_type: holding
  address: 0x128A
  unit_of_measurement: "C"
  value_type: S_WORD
  accuracy_decimals: 1
  filters: 
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Battery Voltage"
  register_type: holding
  address: 0x1290
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 3
  filters: 
    - multiply: 0.001


- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Battery Power"
  register_type: holding
  address: 0x1294
  unit_of_measurement: "W"
  value_type: U_DWORD
  accuracy_decimals: 3
  filters: 
    - multiply: 0.001
  
- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Battery Current"
  register_type: holding
  address: 0x1298
  unit_of_measurement: "A"
  value_type: S_DWORD
  accuracy_decimals: 3
  filters: 
    - multiply: 0.001
  
- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Battery Temperature 1"
  register_type: holding
  address: 0x129C
  unit_of_measurement: "C"
  accuracy_decimals: 1
  filters: 
    - multiply: 0.1
  value_type: S_WORD
  
- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Battery Temperature 2"
  register_type: holding
  address: 0x129E
  unit_of_measurement: "C"
  accuracy_decimals: 1
  filters: 
    - multiply: 0.1
  value_type: S_WORD
  
- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Balance Current"
  register_type: holding
  address: 0x12A4
  unit_of_measurement: "mA"
  value_type: S_WORD
  
- platform: modbus_controller
  modbus_controller_id: bms0
  name: "Battery SOC"
  register_type: holding
  address: 0x12A6
  unit_of_measurement: "%"
  value_type: U_WORD
  bitmask: 0x00FF
text_sensor:

  # Wifi Info
  - platform: wifi_info
    ip_address:
      name: "${name} IP"
    ssid:
      name: "${name} SSID"
    mac_address:
      name: "${name} MAC"    
captive_portal:
    